def passdecryptor(copiedtext):
    copiedtext=copiedtext.replace("7","a")
    copiedtext=copiedtext.replace("G","b")
    copiedtext=copiedtext.replace("2","c")
    copiedtext=copiedtext.replace("O","d")
    copiedtext=copiedtext.replace("L","e")
    copiedtext=copiedtext.replace("C","f")
    copiedtext=copiedtext.replace("Q","g")
    copiedtext=copiedtext.replace("B","h")
    copiedtext=copiedtext.replace("3","i")
    copiedtext=copiedtext.replace("S","j")
    copiedtext=copiedtext.replace("9","k")
    copiedtext=copiedtext.replace("4","l")
    copiedtext=copiedtext.replace("D","m")
    copiedtext=copiedtext.replace("0","n")
    copiedtext=copiedtext.replace("5","o")
    copiedtext=copiedtext.replace("8","p")
    copiedtext=copiedtext.replace("V","q")
    copiedtext=copiedtext.replace("6","r")
    copiedtext=copiedtext.replace("X","s")
    copiedtext=copiedtext.replace("1","t")
    copiedtext=copiedtext.replace("Y","u")
    copiedtext=copiedtext.replace("P","v")
    copiedtext=copiedtext.replace("T","w")
    copiedtext=copiedtext.replace("U","x")
    copiedtext=copiedtext.replace("E","y")
    copiedtext=copiedtext.replace("F","z")
    return copiedtext
