def passencryptor(copiedtext):
    copiedtext=copiedtext.replace("a","J")
    copiedtext=copiedtext.replace("b","G")
    copiedtext=copiedtext.replace("c","Z")
    copiedtext=copiedtext.replace("d","O")
    copiedtext=copiedtext.replace("e","L")
    copiedtext=copiedtext.replace("f","C")
    copiedtext=copiedtext.replace("g","Q")
    copiedtext=copiedtext.replace("h","B")
    copiedtext=copiedtext.replace("i","A")
    copiedtext=copiedtext.replace("j","S")
    copiedtext=copiedtext.replace("k","W")
    copiedtext=copiedtext.replace("l","R")
    copiedtext=copiedtext.replace("m","D")
    copiedtext=copiedtext.replace("n","H")
    copiedtext=copiedtext.replace("o","N")
    copiedtext=copiedtext.replace("p","I")
    copiedtext=copiedtext.replace("q","V")
    copiedtext=copiedtext.replace("r","K")
    copiedtext=copiedtext.replace("s","X")
    copiedtext=copiedtext.replace("t","M")
    copiedtext=copiedtext.replace("u","Y")
    copiedtext=copiedtext.replace("v","P")
    copiedtext=copiedtext.replace("w","T")
    copiedtext=copiedtext.replace("x","U")
    copiedtext=copiedtext.replace("y","E")
    copiedtext=copiedtext.replace("z","F")
    return copiedtext
