def passencryptor(copiedtext):
    copiedtext=copiedtext.replace("a","7")
    copiedtext=copiedtext.replace("b","G")
    copiedtext=copiedtext.replace("c","2")
    copiedtext=copiedtext.replace("d","O")
    copiedtext=copiedtext.replace("e","L")
    copiedtext=copiedtext.replace("f","C")
    copiedtext=copiedtext.replace("g","Q")
    copiedtext=copiedtext.replace("h","B")
    copiedtext=copiedtext.replace("i","3")
    copiedtext=copiedtext.replace("j","S")
    copiedtext=copiedtext.replace("k","9")
    copiedtext=copiedtext.replace("l","4")
    copiedtext=copiedtext.replace("m","D")
    copiedtext=copiedtext.replace("n","0")
    copiedtext=copiedtext.replace("o","5")
    copiedtext=copiedtext.replace("p","8")
    copiedtext=copiedtext.replace("q","V")
    copiedtext=copiedtext.replace("r","6")
    copiedtext=copiedtext.replace("s","X")
    copiedtext=copiedtext.replace("t","1")
    copiedtext=copiedtext.replace("u","Y")
    copiedtext=copiedtext.replace("v","P")
    copiedtext=copiedtext.replace("w","T")
    copiedtext=copiedtext.replace("x","U")
    copiedtext=copiedtext.replace("y","E")
    copiedtext=copiedtext.replace("z","F")
    return copiedtext
