def passdecryptor(copiedtext):
    copiedtext=copiedtext.replace("J","a")
    copiedtext=copiedtext.replace("G","b")
    copiedtext=copiedtext.replace("Z","c")
    copiedtext=copiedtext.replace("O","d")
    copiedtext=copiedtext.replace("L","e")
    copiedtext=copiedtext.replace("C","f")
    copiedtext=copiedtext.replace("Q","g")
    copiedtext=copiedtext.replace("B","h")
    copiedtext=copiedtext.replace("A","i")
    copiedtext=copiedtext.replace("S","j")
    copiedtext=copiedtext.replace("W","k")
    copiedtext=copiedtext.replace("R","l")
    copiedtext=copiedtext.replace("D","m")
    copiedtext=copiedtext.replace("H","n")
    copiedtext=copiedtext.replace("N","o")
    copiedtext=copiedtext.replace("I","p")
    copiedtext=copiedtext.replace("V","q")
    copiedtext=copiedtext.replace("K","r")
    copiedtext=copiedtext.replace("X","s")
    copiedtext=copiedtext.replace("M","t")
    copiedtext=copiedtext.replace("Y","u")
    copiedtext=copiedtext.replace("P","v")
    copiedtext=copiedtext.replace("T","w")
    copiedtext=copiedtext.replace("U","x")
    copiedtext=copiedtext.replace("E","y")
    copiedtext=copiedtext.replace("F","z")
    return copiedtext
