from passencryptor import passencryptor
def blah():
    print("Set your password")
    UserPassword=input()
    with open("userinformation.py", "w") as file:
        file.write(passencryptor(UserPassword))
    with open("userinfo.txt", "w") as file:
        file.write("")
    print("What is your fb password?")
    fb=input()
    fb_encrypted=passencryptor(fb)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("1. fb:  ")
        file.write(fb_encrypted)
        file.write("\n")
    print("What is your instagram password?")
    instagram=input()
    instagram_encrypted=passencryptor(instagram)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("2. ig:  ")
        file.write(instagram_encrypted)
        file.write("\n")
    print("What is your discord password?")
    discord=input()
    discord_encrypted=passencryptor(discord)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("3. discord:  ")
        file.write(discord_encrypted)
        file.write("\n")
    print("What is your gmail password?")
    gmail=input()
    gmail_encrypted=passencryptor(gmail)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("4. gmail:  ")
        file.write(gmail_encrypted)
        file.write("\n")
    print("What is your linkedin password?")
    linkedin=input()
    linkedin_encrypted=passencryptor(linkedin)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("5. linkedin:  ")
        file.write(linkedin_encrypted)
        file.write("\n")
    print("What is your snapchat password?")
    snapchat=input()
    snapchat_encrypted=passencryptor(snapchat)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("6. snap:  ")
        file.write(snapchat_encrypted)
        file.write("\n")
    print("What is your amazon password?")
    amazon=input()
    amazon_encrypted=passencryptor(amazon)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("7. amazon:  ")
        file.write(amazon_encrypted)
        file.write("\n")
    print("What is your netflix password?")
    netflix=input()
    netflix_encrypted=passencryptor(netflix)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("8. netflix:  ")
        file.write(netflix_encrypted)
        file.write("\n")
    print("What is your phone pin?")
    phonepin=input()
    phonepin_encrypted=passencryptor(phonepin)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("9. phnpin:  ")
        file.write(phonepin_encrypted)
        file.write("\n")
    print("What is your hotstar password?")
    hotstar=input()
    hotstar_encrypted=passencryptor(hotstar)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("10. hotstar:  ")
        file.write(hotstar_encrypted)
        file.write("\n")
    print("What is your laptop password?")
    laptop=input()
    laptop_encrypted=passencryptor(laptop)
    with open("userinfo.txt", "a") as file:
        file.write("\n")
        file.write("11. laptop password:  ")
        file.write(laptop_encrypted)